name: Deploy Frontend to S3

on:
  push:
    branches:
      - master
    paths:
      - 'recipe_sharing_app/frontend/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.BURNOOK_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.BURNOOK_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Sync frontend to S3
      run: aws s3 sync . s3://frontend-chapter-3-e08b86da6ed1ac32 --delete
      working-directory: frontend

    - name: Invalidate CloudFront Caches
      run: |
        aws cloudfront create-invalidation --distribution-id EQF3Y3Z48KAQW --paths "/*"

